theme: jekyll-theme-cayman

title: Waddington Optimal Transport
description: Optimal-transport based software tools for single-cell RNA sequencing analysis

repository: robindar/wot

show_downloads: false

navbar_items:
  - title: Home
    url: /
  - title: Documentation
    url: /cli_documentation
  - title: Publications
    url: /
  - title: Examples
    url: /examples
  - title: Github
    url: /github
